import { defineCollection } from 'astro:content';
import { docsSchema } from '@astrojs/starlight/schema';
import { glob } from 'astro/loaders';

// The docs live in ../docs — the same files GitHub renders — and are read in
// place through the src/content/docs symlink, never copied. (The symlink keeps
// every entry's file path inside the project root, which is what Starlight's
// autogenerated sidebar groups match on.) A folder's README.md maps to its
// index route, so docs/README.md is /, docs/types/README.md is /types/, and so
// on. ORCHESTRATION.md is internal and stays off the site.
export const collections = {
  docs: defineCollection({
    loader: glob({
      base: './src/content/docs',
      pattern: ['**/*.md', '!ORCHESTRATION.md'],
      generateId: ({ entry }) =>
        entry
          .replace(/README\.md$/, '')
          .replace(/\.md$/, '')
          .replace(/\/$/, '')
          .toLowerCase() || 'index',
    }),
    schema: docsSchema(),
  }),
};
