#!/usr/bin/env bash
set -euo pipefail

DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    -h|--help)
      echo "Usage: scripts/release.sh [--dry-run]"
      echo "  Cuts a Quilon release from a clean 'main': verifies version consistency,"
      echo "  resolves the codename from release-codenames.tsv, runs the full gate, then"
      echo "  tags v<version> and pushes it (triggers CI, which auto-generates the notes)."
      echo "  --dry-run runs every check and prints what it WOULD do, without tag/push."
      exit 0
      ;;
    *)
      echo "error: unknown argument '$arg' (see --help)" >&2
      exit 2
      ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

die() { echo "error: $*" >&2; exit 1; }
phase() { echo; echo "==> $*"; }

if [[ $DRY_RUN -eq 1 ]]; then
  echo "=== Quilon release (DRY RUN — no tag, no push) ==="
else
  echo "=== Quilon release ==="
fi

phase "Preflight: branch, working tree, and origin/main sync"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
[[ "$BRANCH" == "main" ]] || die "must be on 'main' to release (on '$BRANCH')"
[[ -z "$(git status --porcelain)" ]] || die "working tree is not clean; commit or stash first"

git fetch origin main --tags
LOCAL="$(git rev-parse @)"
REMOTE="$(git rev-parse origin/main)"
[[ "$LOCAL" == "$REMOTE" ]] || die "local 'main' is not in sync with 'origin/main' (local $LOCAL, remote $REMOTE); pull/push first"

phase "Version: reading from root Cargo.toml (single source of truth)"
VERSION="$(grep -m1 '^version = ' Cargo.toml | sed -E 's/^version = "([^"]+)".*/\1/')"
[[ -n "$VERSION" ]] || die "could not read version from Cargo.toml"
TAG="v$VERSION"
echo "    version: $VERSION  ->  tag: $TAG"

RT_VERSION="$(grep -m1 '^version = ' quilon-rt/Cargo.toml | sed -E 's/^version = "([^"]+)".*/\1/')"
[[ "$RT_VERSION" == "$VERSION" ]] || die "quilon-rt/Cargo.toml version ($RT_VERSION) does not match root ($VERSION)"

if git rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
  die "tag '$TAG' already exists locally"
fi
if git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
  die "tag '$TAG' already exists on origin"
fi

phase "Codename: looking up $VERSION in release-codenames.tsv"
# Hitchhiker's-Guide-themed name for this release. Column 1 is a glob (e.g.
# 0.9.* covers the whole 0.9 series), matched against the version. A missing row
# is fine — the release simply carries no quoted name. release.yml resolves the
# same table for the GitHub Release title; this must stay in sync with it.
CODENAME=""
if [[ -f release-codenames.tsv ]]; then
  CODENAME="$(awk -F'\t' -v v="$VERSION" '
    /^#/ || NF < 2 { next }
    { pat = $1; gsub(/\./, "\\.", pat); gsub(/\*/, ".*", pat)
      if (v ~ "^" pat "$") { print $2; exit } }' release-codenames.tsv)"
fi
if [[ -n "$CODENAME" ]]; then
  TITLE="Quilon $TAG \"$CODENAME\""
  echo "    codename: \"$CODENAME\"  ->  title: $TITLE"
else
  TITLE="Quilon $TAG"
  echo "    no codename registered for $VERSION — release title: $TITLE"
fi

phase "CHANGELOG: checking for a dated top-most section for $VERSION (non-blocking)"
# Release notes are auto-generated by release.yml (generate_release_notes from
# merged PRs), so a hand-written CHANGELOG section is no longer required to cut a
# release. This is a soft advisory only; it never blocks. The script never
# generates changelog prose.
TOP_SECTION="$(grep -m1 '^## ' CHANGELOG.md || true)"
if [[ -z "$TOP_SECTION" ]]; then
  echo "    warning: CHANGELOG.md has no '## <version>' section" >&2
elif ! echo "$TOP_SECTION" | grep -qE "^## +${VERSION//./\\.}( |\"|—|\$)"; then
  echo "    warning: top-most CHANGELOG section is not for $VERSION (found: $TOP_SECTION)" >&2
elif ! echo "$TOP_SECTION" | grep -qE '[0-9]{4}-[0-9]{2}-[0-9]{2}'; then
  echo "    warning: CHANGELOG section for $VERSION is not dated (found: $TOP_SECTION)" >&2
else
  echo "    top section: $TOP_SECTION"
fi

phase "Gate: fmt"
cargo fmt --all -- --check

phase "Gate: clippy"
cargo clippy --all-targets --workspace -- -D warnings

phase "Gate: release build"
cargo build --release

phase "Gate: tests (single-threaded)"
# Run single-threaded on purpose: the Boehm-GC parallel-test flake in
# tail_call_test can SIGABRT under the default multi-threaded harness. This is a
# known, pre-existing issue unrelated to the release; -j1 sidesteps it.
cargo test --workspace -- --test-threads=1

if [[ $DRY_RUN -eq 1 ]]; then
  phase "Dry run complete"
  echo "    Release title / tag message: $TITLE"
  echo "    Would create annotated tag:  $TAG  (message: '$TITLE')"
  echo "    Would push:                  git push origin $TAG"
  echo "    Pushing that tag triggers .github/workflows/release.yml, which builds the"
  echo "    binary and publishes the GitHub release (title '$TITLE', notes auto-generated"
  echo "    from merged PRs since the previous tag)."
  echo "    No tag was created and nothing was pushed."
  exit 0
fi

phase "Release: creating and pushing annotated tag $TAG ($TITLE)"
git tag -a "$TAG" -m "$TITLE"
git push origin "$TAG"
echo "    pushed $TAG — .github/workflows/release.yml is now running"

if ! command -v gh >/dev/null 2>&1; then
  phase "Done (gh not installed)"
  echo "    Tag $TAG was pushed; the Release workflow will build and publish."
  echo "    Install the GitHub CLI ('gh') to watch the run and view the release automatically."
  exit 0
fi

phase "Watch: release workflow"
RUN_ID=""
for _ in $(seq 1 30); do
  RUN_ID="$(gh run list --workflow release.yml --branch "$TAG" --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)"
  [[ -n "$RUN_ID" ]] && break
  sleep 2
done
if [[ -n "$RUN_ID" ]]; then
  gh run watch "$RUN_ID" --exit-status || die "release workflow failed — inspect with 'gh run view $RUN_ID --log-failed'"
else
  echo "    could not locate the workflow run yet; check 'gh run list --workflow release.yml'"
fi

phase "Release published"
gh release view "$TAG"
